#!/bin/sh

file=$(basename $1)
dir=$(dirname $1)
cd $dir

[ ${CONTENT_LENGTH:-0} -gt 10000 ] && exit 0

if [ ${CONTENT_LENGTH:-0} -gt 0 ]; then
    POST_FILE=/tmp/post.$$
    export POST_FILE
    if [ "$(dd -h 2>&1 | grep BusyBox)" = "" ]
    then
	dd of=$POST_FILE cbs=$CONTENT_LENGTH conv=block count=1 2>/dev/null
    else
	dd of=$POST_FILE count=$CONTENT_LENGTH bs=1 2>/dev/null
    fi
    bash $file.sh $file < $POST_FILE
    /bin/rm -f $POST_FILE
else
    bash $file.sh $file
fi

